language: node_js
node_js:
  - "stable"
cache:
  directories:
    - frontend/node_modules
script:
  - npm install -g create-react-app
  - cd frontend
  - npm test
  - npm run build
on:
  branch: master